### ISSUE TITLE
Wrong prices and message

### ISSUE THREAD

**Issue by Steedr** [Daniel-Forge-Development/UltimatePokeBuilder#1]
IV price counter
My base price for IV is set to 10.000$
When purchasing only by +1, it will cost 4.960.000$ from 0 -> 31
- First purchase 10k, next 20k, next 30k etc.
When purchasing immediately +31, it will cost 310.000$

Ability price
Hidden ability costs same as normal ability.

When purchasing "Non-Shiny" it shows "pokemon-now-shiny" message.

%cost% in menu only shows a base price for 1 (IV and EV).
Only after you purchased it shows the correct number in that message.
When you try to purchase something what you already have, it shows full price, it should be 0$

**Comment by danorris709** [comment]
Fixed in latest
